### ISSUE TITLE
publish to CRAN / drat?

### ISSUE THREAD

**Issue by jangorecki** [hrbrmstr/qrencoder#1]
Thanks for so fast response on my package request on SO!

Any plans to publish it on CRAN? or your drat repo?

**Comment by hrbrmstr** [comment]
I'll probably setup a drat in the next month or so but it's unlikely this will go to CRAN. They are kinda sticklers about C[++]-based packages trying to at least work on Windows and I have no interest in that (they let a cpl others of mine go, but I'm not really going to lobby for a QR code generator :grinning:). If there is sufficient interest I'll definitely consider it though. I posted it to Twitter and just did a blog post about it, so it might be something more folks need (though I really can't see why unless I'm missing the utility of these things).
