### ISSUE TITLE
plot qr code without attaching raster

### ISSUE THREAD

**Issue by jangorecki** [hrbrmstr/qrencoder#2]
I've found it unable to plot QR code without attaching `raster` package. It is somehow annoying as it makes my package check process produce _NOTE_ on: `* checking dependencies in R code ... NOTE
'library' or 'require' call to ‘raster’ in package code.`
When I try to run them as other suggests I get:

``` r
# Error in image.default(qrencoder::qrencode_raster(to_encode), asp = 1,  : 
#  'z' must be a matrix 
```

Is there any canonical way to solve or is it something that should be fixed in upstream namespaces? I still need to keep qrencoder and raster in Suggests, so I can handle using:

``` r
plotQR <- function(to_encode){
    mar <- par(mar=c(0,0,0,0))
    on.exit(par(mar))
    if(requireNamespace("qrencoder", quietly = TRUE)){
        image(qrencoder::qrencode_raster(to_encode), asp=1, col=c("white", "black"), axes=FALSE, xlab="", ylab="")
    } else {
        plot(c(0, 1), c(0, 1), ann=FALSE, bty="n", type="n", xaxt="n", yaxt="n")
        text(x = 0.5, y = 0.5, "To display QR Code install hrbrmstr/qrencoder package", col = "black")
    }
}
```

reproduce error:

``` r
plotQR("asdasdasdasdasdad")
# Error in image.default(qrencoder::qrencode_raster(to_encode), asp = 1,  : 
#   'z' must be a matrix
library(raster)
# Loading required package: sp
plotQR("asdasdasdasdasdad") # now it works
```

**Comment by hrbrmstr** [comment]
Try `0.0.1.9000`. I just pushed it and it makes `raster` a `Depends` vs `Imports` in `DESCRIPTION`.

**Comment by hrbrmstr** [comment]
Also, there's a CRAN pkg: https://cran.rstudio.com/web/packages/qrcode/index.html for QR code generation now that doesn't require compilation.
